import { describe,it,expect } from 'vitest';
import { ModelRouter, Ledger, Usage, Request, enrichmentKey } from '../src/models/router';
import { config, graph, task, enrichment } from './fixtures';
class MemoryLedger implements Ledger {rows:Usage[]=[];async all(){return this.rows;}async save(row:Usage){this.rows=[...this.rows.filter(r=>r.id!==row.id),structuredClone(row)];}}
function setup(){const c=structuredClone(config);for(const p of Object.values(c.providers)){p.enabled=true;p.model='test-model';p.inputPerMillion=1;p.outputPerMillion=2;}c.monthlyCloudBudget=10;return c;}
const respond=(provider:string,value:unknown=enrichment)=>({status:200,body:provider==='local'?{choices:[{message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:100,completion_tokens:50}}:provider==='openai'?{output:[{content:[{type:'output_text',text:JSON.stringify(value)}]}],usage:{input_tokens:100,output_tokens:50}}:{content:[{type:'text',text:JSON.stringify(value)}],usage:{input_tokens:100,output_tokens:50}}});
describe('model routing and contracts',()=>{
  it('uses LM Studio chat completions and OpenAI Responses with validated schema output',async()=>{const requests:Request[]=[],ledger=new MemoryLedger(),c=setup();const r=new ModelRouter(async()=>c,()=> 'secret',async req=>{requests.push(req);return respond(req.url.includes('1234')?'local':'openai');},ledger,async()=>{});const result=await r.enrich(task(),graph);expect(result.provider).toBe('openai');expect(requests[0].url).toBe('http://127.0.0.1:1234/v1/chat/completions');expect((requests[0].body as any).response_format.type).toBe('json_schema');expect((requests[1].body as any).text.format.type).toBe('json_schema');expect((requests[1].body as any).store).toBe(false);expect(ledger.rows.every(r=>r.status==='ok')).toBe(true);expect(JSON.stringify(ledger.rows)).not.toContain('secret');});
  it('routes complex work to Anthropic with current output_config shape',async()=>{const c=setup(),requests:Request[]=[];const r=new ModelRouter(async()=>c,()=> 'secret',async req=>{requests.push(req);return respond(req.url.includes('1234')?'local':'anthropic',{...enrichment,complex:true});},new MemoryLedger(),async()=>{});expect((await r.enrich(task(),graph)).provider).toBe('anthropic');expect((requests[1].body as any).output_config.format.type).toBe('json_schema');expect(requests[1].headers['anthropic-version']).toBe('2023-06-01');});
  it('falls back on cloud errors and retries transient failures at most twice',async()=>{let openai=0;const r=new ModelRouter(async()=>setup(),()=> 'secret',async req=>{if(req.url.includes('openai')){openai++;return {status:503,body:{}};}return respond(req.url.includes('1234')?'local':'anthropic');},new MemoryLedger(),async()=>{});expect((await r.enrich(task(),graph)).provider).toBe('anthropic');expect(openai).toBe(3);});
  it('continues with confident local scores when cloud is paused',async()=>{const c=setup();c.monthlyCloudBudget=0;const requests:Request[]=[];const r=new ModelRouter(async()=>c,()=> 'secret',async req=>{requests.push(req);return respond('local');},new MemoryLedger(),async()=>{});expect((await r.enrich(task(),graph)).provider).toBe('lmstudio');expect(requests).toHaveLength(1);});
  it('does not accept low-confidence local results when escalation is unavailable',async()=>{const c=setup();c.monthlyCloudBudget=0;const r=new ModelRouter(async()=>c,()=>null,async()=>respond('local',{...enrichment,confidence:.5}),new MemoryLedger(),async()=>{});await expect(r.enrich(task(),graph)).rejects.toThrow();});
  it('recovers from an unavailable LM Studio server',async()=>{const r=new ModelRouter(async()=>setup(),()=> 'secret',async req=>{if(req.url.includes('1234'))throw new Error('ECONNREFUSED');return respond('openai');},new MemoryLedger(),async()=>{});expect((await r.enrich(task(),graph)).provider).toBe('openai');});
  it('rejects malformed JSON and unknown goal identifiers',async()=>{const c=setup();c.providers.lmstudio.enabled=false;c.providers.anthropic.enabled=false;const r=new ModelRouter(async()=>c,()=> 'secret',async()=>respond('openai',{...enrichment,goalId:'invented'}),new MemoryLedger(),async()=>{});await expect(r.enrich(task(),graph)).rejects.toThrow('unknown L3');const bad=new ModelRouter(async()=>c,()=> 'secret',async()=>({status:200,body:{output:[{content:[{type:'output_text',text:'bad json'}]}]}}),new MemoryLedger(),async()=>{});await expect(bad.enrich(task(),graph)).rejects.toThrow('invalid response');});
  it('reserves budget before requests and preserves reservations on ambiguous failures',async()=>{const c=setup();c.providers.lmstudio.enabled=false;c.providers.anthropic.enabled=false;c.monthlyCloudBudget=.02;const ledger=new MemoryLedger();let calls=0;const r=new ModelRouter(async()=>c,()=> 'secret',async()=>{calls++;expect((await ledger.all()).at(-1)?.status).toBe('reserved');throw new Error('timeout');},ledger,async()=>{});await expect(r.enrich(task(),graph)).rejects.toThrow();expect(calls).toBeLessThanOrEqual(2);expect(ledger.rows.reduce((n,r)=>n+r.cost,0)).toBeGreaterThan(0);});
  it('invalidates cache for meaningful task, graph and rubric changes',()=>{const t=task(),key=enrichmentKey(t,graph,config);t.title+=' edited';expect(enrichmentKey(t,graph,config)).not.toBe(key);expect(enrichmentKey(task(),{...graph,version:2},config)).not.toBe(key);expect(enrichmentKey(task(),graph,{...config,rubricVersion:2})).not.toBe(key);});
  it('validates the graph proposal before returning it',async()=>{const c=setup();const r=new ModelRouter(async()=>c,()=> 'secret',async()=>respond('anthropic',graph),new MemoryLedger(),async()=>{});expect((await r.draft('My goals',graph)).goals).toHaveLength(5);});
});
