import { it,expect } from 'vitest';
import { Store, paths } from '../src/storage/store';
import { Service, MarkdownLedger } from '../src/service';
import { ModelRouter } from '../src/models/router';
import { writeNote } from '../src/storage/markdown';
import { MemoryIO, config, graph, enrichment } from './fixtures';
import { localDate } from '../src/core/model';
async function setup(){const io=new MemoryIO(),store=new Store(io);await store.init();const c=structuredClone(config);c.providers.lmstudio.model='test';await store.put(paths.config,writeNote(c,'Settings notes'));await store.put(paths.goals,writeNote(graph,'Goals notes'));const router=new ModelRouter(()=>store.config(),()=>null,async()=>({status:200,body:{choices:[{message:{content:JSON.stringify(enrichment)}}]}}),new MarkdownLedger(store),async()=>{});const service=new Service(store,router);await service.refresh();return {io,store,router,service};}
it('runs capture → enrichment → session → completion → progress and persists restart state',async()=>{const {service,store,router,io}=await setup();await service.capture('Send sponsor letters');while(service.busy)await new Promise(r=>setTimeout(r,5));await service.refresh();expect(service.tasks[0].inferred?.goalId).toBe('event');const id=service.tasks[0].id;await service.session(id,20);await service.toggle(id,true);expect(service.tasks[0].snapshot?.points).toBeCloseTo(68.8);const next=new Service(store,router);await next.refresh(true);expect(next.tasks[0].status).toBe('done');expect(next.tasks[0].sessions[0].minutes).toBe(20);expect(await io.read(paths.progress)).toContain('68.8');await next.toggle(id,false);expect(await io.read(paths.progress)).toContain('0.0 all time');});
it('discards an in-flight result after a task edit',async()=>{const {service,store,router}=await setup();let resolve!:()=>void;const waiting=new Promise<void>(r=>resolve=r);router.enrich=async()=>{await waiting;return {data:enrichment,provider:'mock'};};await store.capture('Before');await service.refresh();const running=service.enrich();await new Promise(r=>setTimeout(r,5));await store.updateTask(service.tasks[0].id,t=>({...t,title:'After'}));resolve();await running;expect((await store.taskFiles())[0].task.inferred).toBe(null);});
it('preserves user prose when daily plans and weekly insights refresh',async()=>{const {service,io}=await setup();const p=`Noiseless/Days/${localDate()}.md`;await io.process(p,t=>t+'\nMy meeting notes\n');await service.refresh();expect(await io.read(p)).toContain('My meeting notes');expect(await io.read(paths.config)).toContain('Settings notes');});
it('retains capture and last valid scores when every provider fails',async()=>{const {service,router,store}=await setup();router.enrich=async()=>{throw new Error('Models unavailable');};await store.capture('Keep this task');await service.refresh();await service.enrich();expect(service.tasks[0].title).toBe('Keep this task');expect(service.tasks[0].pending).toBe('Models unavailable');expect(await store.io.read(paths.everything)).toContain('Keep this task');});
it('does not apply an in-flight result after the plugin is disabled',async()=>{const {service,router,store}=await setup();let finish!:()=>void;const waiting=new Promise<void>(resolve=>finish=resolve);router.enrich=async()=>{await waiting;return {data:enrichment,provider:'mock'};};await store.capture('Preserve while disabled');await service.refresh();const running=service.enrich();service.stopped=true;finish();await running;expect((await store.taskFiles())[0].task.inferred).toBe(null);});
