import { it,expect } from 'vitest';
import { captureLines, managed, patchNote, readNote, taskNote, writeNote } from '../src/storage/markdown';
import { paths, Store } from '../src/storage/store';
import { taskSchema } from '../src/core/model';
import { MemoryIO, task, graph } from './fixtures';

it('round-trips task metadata, YAML characters, unknown properties and prose',()=>{const t=task();t.title='A: "title" #tag';const text=writeNote({...t,custom:'keep me'},'\nHandwritten notes.\n');const next=patchNote(text,taskSchema,t=>({...t,status:'blocked' as const}));expect(readNote(next,taskSchema).meta.custom).toBe('keep me');expect(next).toContain('Handwritten notes.');expect(readNote(next,taskSchema).data.title).toBe(t.title);});
it('captures identical text as distinct tasks and reruns idempotently',()=>{const input='<!-- noiseless:capture:start -->\nEmail Sam\n- Email Sam\n- [x] File forms\n<!-- noiseless:capture:end -->';const a=captureLines(input),b=captureLines(a.text);expect(a.items).toHaveLength(3);expect(new Set(a.items.map(i=>i.id)).size).toBe(3);expect(b).toEqual(a);expect(a.items[2].done).toBe(true);});
it('preserves nonmanaged notes and rejects broken section markers',()=>{const result=managed('My notes\n','summary','Generated');expect(managed(result,'summary','New')).toContain('My notes');expect(()=>managed('<!-- noiseless:summary:start -->','summary','bad')).toThrow();});
it('recovers capture after markers were written but task creation was interrupted',async()=>{const io=new MemoryIO(),store=new Store(io);await store.init();await io.process(paths.everything,t=>t.replace('<!-- noiseless:capture:end -->','Email someone\n<!-- noiseless:capture:end -->'));await io.process(paths.everything,t=>captureLines(t).text);await store.ingest();await store.ingest();expect(await store.taskFiles()).toHaveLength(1);});
it('supports source checkbox completion and a canonical edit without resurrecting stale capture values',async()=>{const io=new MemoryIO(),store=new Store(io);await store.init();await store.capture('Draft letter');const {task:t}= (await store.taskFiles())[0];await store.updateTask(t.id,t=>({...t,title:'Improved title',status:'done'}));await store.ingest();expect((await store.taskFiles())[0].task.title).toBe('Improved title');expect((await store.taskFiles())[0].task.status).toBe('done');await io.process(paths.everything,t=>t.replace('- [ ] Draft letter','- [x] Revised letter'));await store.ingest();expect((await store.taskFiles())[0].task.title).toBe('Revised letter');});
it('finds renamed task files and rejects duplicate IDs rather than losing data',async()=>{const io=new MemoryIO(),store=new Store(io);await store.init();await store.capture('Task');const f=(await store.taskFiles())[0];io.files.set('Noiseless/Tasks/Renamed.md',io.files.get(f.path)!);io.files.delete(f.path);await store.updateTask(f.task.id,t=>({...t,status:'blocked'}));expect((await store.taskFiles())[0].task.status).toBe('blocked');io.files.set('Noiseless/Tasks/Copy.md',taskNote(f.task));await expect(store.taskFiles()).rejects.toThrow('Duplicate');});
it('serializes concurrent updates and retains unrelated user fields',async()=>{const io=new MemoryIO(),store=new Store(io);await store.init();await store.capture('Task');const id=(await store.taskFiles())[0].task.id;await Promise.all([store.updateTask(id,t=>({...t,provider:'test'})),store.updateTask(id,t=>({...t,status:'blocked'}))]);const t=(await store.taskFiles())[0].task;expect(t.provider).toBe('test');expect(t.status).toBe('blocked');});
it('approves only valid drafts and retains the previous graph',async()=>{const io=new MemoryIO(),store=new Store(io);await store.init();await io.process(paths.draft,()=>writeNote(graph,'Proposal'));await store.approveDraft();expect((await store.graph()).goals).toHaveLength(5);expect((await io.list()).some(p=>p.includes('History/Goals-'))).toBe(true);});
